# Google Cloud API Gateway OpenAPI specification.
#
# This configuration follows the OpenAPI 3.0.x specification with the addition
# of Google-specific extensions.
#
# See:
#   - https://spec.openapis.org/oas/v3.0.4.html
#   - https://docs.cloud.google.com/api-gateway/docs/oasv3-extensions
openapi: 3.0.4
info:
  title: MCP Auth
  description: API for MCP Auth
  version: 0.1.0
x-google-api-management:
  backends:
    cloud_run:
      address: ${cloud_run_uri}
x-google-backend: cloud_run
paths:
  /:
    get:
      description: Root endpoint.
      operationId: root__get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful Response
      summary: Root
  /.well-known/oauth-protected-resource:
    get:
      description: "Returns the OAuth 2.0 Protected Resource Metadata (RFC 9728).
        See: https://datatracker.ietf.org/doc/html/rfc9728"
      operationId: protected_resource_metadata__well_known_oauth_protected_resource_get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful Response
      summary: Protected Resource Metadata
      tags:
        - metadata
  /.well-known/openid-configuration:
    get:
      description: "Returns the OAuth 2.0 Authorization Server Metadata (RFC 8414).
        See: https://datatracker.ietf.org/doc/html/rfc8414"
      operationId: authorization_server_metadata__well_known_openid_configuration_get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful Response
      summary: Authorization Server Metadata
      tags:
        - metadata
  /health:
    get:
      description: Return health check status.
      operationId: health_health_get
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful Response
      summary: Health
      tags:
        - health
